theme: jekyll-theme-midnight
title: Bruno's Portfolio
description: Data Analytics projects, visualizations, and tech explorations by Bruno del Palacio Rodr√≠guez
logo: https://avatars.githubusercontent.com/u/brunodpl
show_downloads: true
